### ISSUE TITLE
Comment on the model

### ISSUE THREAD

**Issue by Xapulc** [eduardomazevedo/admrw-ab-replication-code#1]
Hello! Thank you for article.

I have the following question on the model. Density g characterises the a priori distribution of the t-statistic of the criterion. This function is fixed throughout the article. But value of t-statistic depends on sample proportions and sample sizes. In particular, the distribution of t-statistic for small samples will be completely different than for large sample. It seems to me that it follows that the density g cannot be used for different sample sizes, and the model is not relevant. What do you think about this remark?

**Comment by eduardomazevedo** [comment]
Hi. First of all, happy Sunday to you!

g() is the density of the quality delta of an idea. This is the true quality, not what is measured in the experiment. For example, in a marketing setting you may define delta as how many % does the idea increase conversion rate. That is why g is the same regardless of the sample size. We sometimes use the t-distribution for g because it is a good fit for data from very large Internet products. See pp. 6-7 here https://eduardomazevedo.github.io/papers/azevedo-et-al-ab.pdf

Hope that this is useful.
